name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: LImoritakeU/paperless-ngx
        ref: main
        token: ${{ secrets.PAT }}
    - name: Build the Docker image
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        docker build . --file Dockerfile --tag ghcr.io/limoritakeu/paperless-ngx:latest
        docker login --username LImoritakeU --password "$PAT" ghcr.io
        docker push ghcr.io/limoritakeu/paperless-ngx:latest
